apiVersion: v1
kind: Service
metadata:
  name: app-fiapx-core-svc-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30019
  selector:
    app: app-fiapx-core-pod