apiVersion: v1
kind: ConfigMap
metadata:
  name: app-fiapx-core-configmap
data:
  MYSQL_URL: jdbc:mysql://shogun-pagamento-database.crax9dqhkq1j.us-east-1.rds.amazonaws.com:3306/db_soat_pagamento?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC