apiVersion: v1
kind: Service
metadata:
  name: app-fiapx-core-svc-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8091
      nodePort: 30012
  selector:
    app: app-fiapx-core-pod