apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-fiapx-core-deployment
  labels:
    app: app-fiapx-core-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-fiapx-core-pod
  template:
    metadata:
      labels:
        app: app-fiapx-core-pod
    spec:
      serviceAccountName: rds-access-sa
      containers:
        - name: app-fiapx-core-container
          image: 6soatgroup74/fiapx-core:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-fiapx-core-configmap
          readinessProbe:
            httpGet:
              path: actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
          startupProbe:
            httpGet:
              path: actuator/health
              port: 8080
            initialDelaySeconds: 30
            failureThreshold: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 500m